language: julia
os:
  - linux
  - osx
julia:
  - 0.3
  - 0.4
  - nightly
notifications:
  email: false
before_install:
  - cd ..
  - git clone https://github.com/wookay/CITestIJulia.jl.git IJulia.jl
  - cd IJulia.jl
  - if [ ${TRAVIS_OS_NAME} == "osx" ]; then brew update >/dev/null 2>&1; fi
script:
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
  - julia -e 'Pkg.clone(pwd()); Pkg.build("IJulia")'
  - julia -e 'Pkg.test("IJulia"; coverage=true)'
after_success:
  #- julia --color=yes -e 'cd(Pkg.dir("IJulia")); Pkg.add("Coverage"); using Coverage;
  #  Coveralls.submit(Coveralls.process_folder())'
